/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Amount = IDL.Float64;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TransactionId = IDL.Text;
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Address = IDL.Text;
export const Time = IDL.Int;
export const TransactionType = IDL.Variant({
  'receive' : IDL.Null,
  'send' : IDL.Null,
  'stealthSend' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'toFrom' : Address,
  'isHidden' : IDL.Bool,
  'timestamp' : Time,
  'txType' : TransactionType,
  'amount' : IDL.Float64,
});
export const TxId = IDL.Text;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBalance' : IDL.Func([], [Amount], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPrincipal' : IDL.Func([], [IDL.Text], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'receiveICP' : IDL.Func([Address, Amount], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoData' : IDL.Func([], [], []),
  'sendICP' : IDL.Func([Address, Amount, IDL.Bool], [IDL.Text], []),
  'toggleTransactionVisibility' : IDL.Func([TxId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Amount = IDL.Float64;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TransactionId = IDL.Text;
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Address = IDL.Text;
  const Time = IDL.Int;
  const TransactionType = IDL.Variant({
    'receive' : IDL.Null,
    'send' : IDL.Null,
    'stealthSend' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'toFrom' : Address,
    'isHidden' : IDL.Bool,
    'timestamp' : Time,
    'txType' : TransactionType,
    'amount' : IDL.Float64,
  });
  const TxId = IDL.Text;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBalance' : IDL.Func([], [Amount], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPrincipal' : IDL.Func([], [IDL.Text], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'receiveICP' : IDL.Func([Address, Amount], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoData' : IDL.Func([], [], []),
    'sendICP' : IDL.Func([Address, Amount, IDL.Bool], [IDL.Text], []),
    'toggleTransactionVisibility' : IDL.Func([TxId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };